development:
  adapter: postgresql
  encoding: unicode
  database: openpgp_ca_development
  pool: 5
  username: grant
  password: Hodf^pSUd?ll;moS,9:M1'z5Hm+~3|EZBQKq)N!4-gP\uBcCkMK4?CxrNse\AWv,

test:
  adapter: postgresql
  encoding: unicode
  database: openpgp_ca_test
  pool: 5
  username: grant
  password: Hodf^pSUd?ll;moS,9:M1'z5Hm+~3|EZBQKq)N!4-gP\uBcCkMK4?CxrNse\AWv,

production:
   adapter: postgresql
   encoding: unicode
   database: openpgp_ca_production
   pool: 5
   username: root
   password:

